//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace msit116apexLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundGoods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FundGoods()
        {
            this.ShoppingCart = new HashSet<ShoppingCart>();
        }
    
        public string GoodID { get; set; }
        public int FundID { get; set; }
        public string FundAreaCode { get; set; }
        public string FundTypeCode { get; set; }
        public string FundCurrencyCode { get; set; }
        public string FundCpyCode { get; set; }
        public string ChargeFeeCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> ClickRate { get; set; }
    
        public virtual ChargeFee ChargeFee { get; set; }
        public virtual FundArea FundArea { get; set; }
        public virtual FundCompany FundCompany { get; set; }
        public virtual FundCurrency FundCurrency { get; set; }
        public virtual FundMaster FundMaster { get; set; }
        public virtual FundType FundType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
    }
}
