//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace msit116apexLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview_records
    {
        public int InterviewID { get; set; }
        public string UserID { get; set; }
        public string Interviewer_Name { get; set; }
        public string Interviewee_Name { get; set; }
        public string InterviewReason { get; set; }
        public Nullable<int> C_Type_ID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string C_Location { get; set; }
        public string InterviewContent { get; set; }
    
        public virtual InterviewType InterviewType { get; set; }
    }
}
