//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace msit116apexLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int ID { get; set; }
        public int Lav_ID { get; set; }
        public System.DateTime Lav_StartTime { get; set; }
        public System.DateTime Lac_EndTime { get; set; }
        public int Lac_LeavecategoryID { get; set; }
        public int Lac_Agent { get; set; }
        public string Lac_Tag { get; set; }
        public int Lav_ReviewID { get; set; }
        public string LeaveImage { get; set; }
        public byte[] BytesImage { get; set; }
        public string LavSupervisor { get; set; }
        public Nullable<decimal> Lav_Day { get; set; }
    
        public virtual Leavecategory Leavecategory { get; set; }
        public virtual Review Review { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
