//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace msit116apexLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingOrderHistory
    {
        public int POH_ID { get; set; }
        public string POH_StockID { get; set; }
        public bool POH_BuySold { get; set; }
        public decimal POH_Price { get; set; }
        public int POH_Volume { get; set; }
        public System.DateTime POH_OrderTime { get; set; }
        public string POH_EmpID { get; set; }
        public int POH_CheckCancel { get; set; }
        public string POH_AccountID { get; set; }
    
        public virtual StockInfo StockInfo { get; set; }
    }
}
