//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace msit116apexLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockInfo()
        {
            this.PendingOrderHistory = new HashSet<PendingOrderHistory>();
            this.SelfSelectedStockList = new HashSet<SelfSelectedStockList>();
            this.StockInfoHistory = new HashSet<StockInfoHistory>();
            this.StockTradingRecord = new HashSet<StockTradingRecord>();
            this.StockTreasury = new HashSet<StockTreasury>();
        }
    
        public string SI_StockID { get; set; }
        public string SI_StockName { get; set; }
        public int SI_CategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingOrderHistory> PendingOrderHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfSelectedStockList> SelfSelectedStockList { get; set; }
        public virtual StockCategoriesList StockCategoriesList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInfoHistory> StockInfoHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTradingRecord> StockTradingRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTreasury> StockTreasury { get; set; }
    }
}
