//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace msit116apexLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTreasury
    {
        public int ST_ID { get; set; }
        public string ST_StockID { get; set; }
        public decimal ST_Price { get; set; }
        public int ST_Volume { get; set; }
        public string ST_EmpID { get; set; }
        public System.DateTime ST_EnterTreasuryTime { get; set; }
        public string ST_AccountID { get; set; }
    
        public virtual StockInfo StockInfo { get; set; }
    }
}
