//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace msit116apexLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uRolePowerConfirmHistory
    {
        public int uRolePowerConfirmSn { get; set; }
        public string UserID { get; set; }
        public Nullable<int> powerID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> limitDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public int state { get; set; }
        public int urpchSn { get; set; }
    }
}
