//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace msit116apexLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uRolePowerConfirmHistoryConfirmData
    {
        public int uRolePowerConfirmHistorySn { get; set; }
        public string cTableName { get; set; }
        public string primaryColumnName { get; set; }
        public string primaryColumnValue { get; set; }
        public string execAction { get; set; }
        public int state { get; set; }
        public string primaryColumnType { get; set; }
        public int urpchcdSn { get; set; }
    }
}
